name: Build and deploy ASP.Net Core app to Azure Web App - app-service-macedo-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore AzureDeployStudy/AzureDeployStudy/AzureDeployStudy.csproj

      - name: Build with dotnet
        run: dotnet build AzureDeployStudy/AzureDeployStudy/AzureDeployStudy.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish AzureDeployStudy/AzureDeployStudy/AzureDeployStudy.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_583D5389BD184876958E6DF72946465E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1E09C505E844D18A8FD642D5C025B0D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C35CECCC1374260BC88DFC545809F22 }}

      - name: Get Runner IP
        id: get-runner-ip
        run: |
          $RUNNER_IP = Invoke-RestMethod -Uri https://api.ipify.org
          echo "RUNNER_IP=$RUNNER_IP" >> $env:GITHUB_ENV
          echo "FIREWALL_RULE_NAME=github-action-runner-rule" >> $env:GITHUB_ENV

      - name: Add Runner IP to SQL Firewall
        run: |
          az sql server firewall-rule create `
            --resource-group "app-service-new" `
            --server "app-service-server" `
            --name "${env:FIREWALL_RULE_NAME}" `
            --start-ip-address "${env:RUNNER_IP}" `
            --end-ip-address "${env:RUNNER_IP}"

      - name: Run .NET EF Migrations
        env:
          CustomerConnectionString: ${{ secrets.CustomerConnectionString }}
        run: |
          dotnet tool install --global dotnet-ef
          setx PATH "%PATH%;%USERPROFILE%\.dotnet\tools"
          dotnet ef database update `
            --project AzureDeployStudy/AzureDeployStudy/AzureDeployStudy.csproj `
            --startup-project AzureDeployStudy/AzureDeployStudy/AzureDeployStudy.csproj `
            --connection "${{ secrets.CustomerConnectionString }}"

      - name: Remove Runner IP from SQL Firewall
        if: always()
        run: |
          az sql server firewall-rule delete `
            --resource-group "app-service-new" `
            --server "app-service-server" `
            --name "${env:FIREWALL_RULE_NAME}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-service-macedo-2'
          slot-name: 'Production'
          package: .  
